services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8000:80"
    volumes:
      - ./:/opt/potion
    depends_on:
      - php
      - mysql
      - mailpit
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/opt/potion
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
      DB_HOST: mysql
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      XDG_CONFIG_HOME: /tmp
      MYSQL_ATTR_SSL_CA: ''
      MAIL_HOST: mailpit
  mysql:
    image: mysql:8.1
    command: --tls-version='TLSv1.2'
    ports: [ '${DB_PORT}:3306' ]
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.docker:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
  mysql-data:
  mailpit-data:
