name: Deploy to Elastic Beanstalk

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Create .env file
      uses: iamsauravsharma/create-dotenv@v3.1.1
      with:
        input-prefix: 'IN_'
      env:
        IN_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        IN_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IN_JWT_PRIVATE_KEY: ${{ vars.JWT_PRIVATE_KEY }}
        IN_JWT_PUBLIC_KEY: ${{ vars.JWT_PUBLIC_KEY }}
        IN_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        IN_APP_KEY: ${{ secrets.APP_KEY }}
        IN_APP_URL: ${{ vars.APP_URL }}
        IN_MAIL_MAILER: ${{ vars.MAIL_MAILER }}
        IN_STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
        IN_STRIPE_PAYMENT_METHOD_CONFIG: ${{ vars.STRIPE_PAYMENT_METHOD_CONFIG }}
        IN_STRIPE_TAX_RATES: ${{ vars.STRIPE_TAX_RATES }}
        IN_STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: POTION
        environment_name: potion-prod
        region: us-east-1
        deployment_package: deploy.zip