name: Deploy to AWS Lambda

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      environment:
        type: environment
env:
  ENVIRONMENT: ${{ inputs.environment || 'Production' }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'Production' }}
    steps:
      # Check out a copy of your repository.
      - name: Checkout code
        uses: actions/checkout@v4

      # Use parameter expansion to make environment lowercase.
      - name: Downcase environment
        run: |
          echo "ENVIRONMENT_LC=${ENVIRONMENT,,}" >>${GITHUB_ENV}

      - name: Create JWT Tokens
        run: |
          mkdir storage/certs
          cat << EOF > storage/certs/jwt-rsa-4096-public.pem
          ${{ secrets.JWT_PUBLIC_KEY_CONTENTS }}
          EOF
          cat << EOF > storage/certs/jwt-rsa-4096-private.pem
          ${{ secrets.JWT_PRIVATE_KEY_CONTENTS }}
          EOF

      # Set up PHP environment.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      # Install Composer dependencies with the specified options.
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--prefer-dist --optimize-autoloader --no-dev"

      # Deploy your application to AWS Lambda using the Serverless Framework.
      - name: Deploy to AWS Lambda
        uses: serverless/github-action@v3
        with:
          args: deploy --stage=${{ env.ENVIRONMENT_LC }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          JWT_PRIVATE_KEY: ${{ vars.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ vars.JWT_PUBLIC_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_USERNAME: ${{ secrets.PLANETSCALE_USERNAME }}
          DB_PASSWORD: ${{ secrets.PLANETSCALE_PASSWORD }}
          DB_HOST: ${{ vars.PLANETSCALE_HOST }}
          DB_DATABASE: ${{ vars.DB_DATABASE }}
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_URL: ${{ vars.APP_URL }}

      - name: Populate Roles and Permissions
        uses: serverless/github-action@v3
        with:
          args: bref:cli --args="permission:populate" --stage=${{ env.ENVIRONMENT_LC }}
