name: PHPStan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  phpstan:
    name: Run PHPStan Analysis
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
        # Set up PHP environment.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          path: app/
          php_version: "8.4"