name: PHPStan

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  phpstan:
    name: Run PHPStan Analysis
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
        # Set up PHP environment.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
        with:
          args: analyse app/