name: PHPStan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      # Install Composer dependencies with the specified options.
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--prefer-dist --optimize-autoloader"

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse app/