name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  php-tests:
    runs-on: ubuntu-latest
    environment: development

    strategy:
      fail-fast: false
      matrix:
        php: [8.3]
        coverage: [xdebug]
    name: 'Tests - PHP ${{ matrix.php }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create JWT Tokens
        run: |
          mkdir storage/certs
          cat << EOF > storage/certs/jwt-rsa-4096-public.pem
          ${{ secrets.JWT_PUBLIC_KEY_CONTENTS }}
          EOF
          cat << EOF > storage/certs/jwt-rsa-4096-private.pem
          ${{ secrets.JWT_PRIVATE_KEY_CONTENTS }}
          EOF

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring json openssl
          coverage: ${{ matrix.coverage }}
          ini-values: memory_limit=-1

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--prefer-dist --optimize-autoloader"

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          JWT_PRIVATE_KEY: ${{ vars.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ vars.JWT_PUBLIC_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          STRIPE_PAYMENT_METHOD_CONFIG: ${{ vars.STRIPE_PAYMENT_METHOD_CONFIG }}
          STRIPE_TAX_RATES: ${{ vars.STRIPE_TAX_RATES }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}